### ISSUE TITLE
Exhibitera Hub: Pydantic Dependency Issue

### ISSUE THREAD

**Issue by alexaverill** [Cosmic-Chatter/Exhibitera#21]
@forceflow1049 
I was running into an issue with the pydantic dependency when I went to get things spun up this evening to start testing the mapping integration with the Hub ( and with getting the Apps running). 

I did some digging and found that updating pydantic to `pydantic==1.10.16` in the requirements.txt got things working. 

If you think updating is the way to go I can put that in a PR and send it your way. 

[source 1](https://github.com/langchain-ai/langgraph/issues/639) [source 2](https://github.com/pydantic/pydantic-core/issues/1366)
My python version: Python 3.12.4

Error Message: 
```
Traceback (most recent call last):
  File "/Users/aaverill/Code/Exhibitera/Alex/Exhibitera/exhibitera/hub/Exhibitera_Hub.py", line 29, in <module>
    from fastapi import Body, FastAPI, File, Response, Request, UploadFile
  File "/Users/aaverill/Code/Exhibitera/Alex/Exhibitera/exhibitera/hub/venv/lib/python3.12/site-packages/fastapi/__init__.py", line 7, in <module>
    from .applications import FastAPI as FastAPI
  File "/Users/aaverill/Code/Exhibitera/Alex/Exhibitera/exhibitera/hub/venv/lib/python3.12/site-packages/fastapi/applications.py", line 16, in <module>
    from fastapi import routing
  File "/Users/aaverill/Code/Exhibitera/Alex/Exhibitera/exhibitera/hub/venv/lib/python3.12/site-packages/fastapi/routing.py", line 22, in <module>
    from fastapi import params
  File "/Users/aaverill/Code/Exhibitera/Alex/Exhibitera/exhibitera/hub/venv/lib/python3.12/site-packages/fastapi/params.py", line 5, in <module>
    from fastapi.openapi.models import Example
  File "/Users/aaverill/Code/Exhibitera/Alex/Exhibitera/exhibitera/hub/venv/lib/python3.12/site-packages/fastapi/openapi/models.py", line 124, in <module>
    class Schema(BaseModelWithConfig):
  File "/Users/aaverill/Code/Exhibitera/Alex/Exhibitera/exhibitera/hub/venv/lib/python3.12/site-packages/pydantic/main.py", line 286, in __new__
    cls.__try_update_forward_refs__()
  File "/Users/aaverill/Code/Exhibitera/Alex/Exhibitera/exhibitera/hub/venv/lib/python3.12/site-packages/pydantic/main.py", line 808, in __try_update_forward_refs__
    update_model_forward_refs(cls, cls.__fields__.values(), cls.__config__.json_encoders, localns, (NameError,))
  File "/Users/aaverill/Code/Exhibitera/Alex/Exhibitera/exhibitera/hub/venv/lib/python3.12/site-packages/pydantic/typing.py", line 554, in update_model_forward_refs
    update_field_forward_refs(f, globalns=globalns, localns=localns)
  File "/Users/aaverill/Code/Exhibitera/Alex/Exhibitera/exhibitera/hub/venv/lib/python3.12/site-packages/pydantic/typing.py", line 520, in update_field_forward_refs
    field.type_ = evaluate_forwardref(field.type_, globalns, localns or None)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aaverill/Code/Exhibitera/Alex/Exhibitera/exhibitera/hub/venv/lib/python3.12/site-packages/pydantic/typing.py", line 66, in evaluate_forwardref
    return cast(Any, type_)._evaluate(globalns, localns, set())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ForwardRef._evaluate() missing 1 required keyword-only argument: 'recursive_guard'
```

**Comment by forceflow1049** [comment]
Hi @alexaverill, I independently discovered this issue a couple of weeks ago while compiling the final binaries for v5.1. I updated both `requirements.txt` (for Hub and Apps) to `pydantic==1.10.17`. If you pull Dev_5.2, you should see the fix!
